"""atualizaçao das tabelas

Revision ID: e962d64451ad
Revises: 53a24d6606df
Create Date: 2021-12-10 14:39:46.879934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e962d64451ad'
down_revision = '53a24d6606df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('stores', sa.Column('state', sa.String(length=20), nullable=False))
    op.drop_column('stores', 'store_img')
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.add_column('stores', sa.Column('store_img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('stores', 'state')
    op.drop_column('stores', 'city')
    # ### end Alembic commands ###
